"""Constraint

Revision ID: 734e95f14e86
Revises: 006e2f4c8f84
Create Date: 2026-08-29 12:59:29.186696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '734e95f14e86'
down_revision: Union[str, Sequence[str], None] = '006e2f4c8f84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_courses_teacher_id'), 'courses', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_teacher_id'), table_name='courses')
    # ### end Alembic commands ###
