"""Constraint

Revision ID: 734e95f14e86
Revises: 006e2f4c8f84
Create Date: 2026-08-29 12:59:29.186696

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "734e95f14e86"
down_revision: str | Sequence[str] | None = "006e2f4c8f84"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_courses_teacher_id"), "courses", ["teacher_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_courses_teacher_id"), table_name="courses")
    # ### end Alembic commands ###
