"""create enrollments table

Revision ID: eb763977b665
Revises: 7d0785af3657
Create Date: 2026-08-11 10:04:48.640743

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "eb763977b665"
down_revision: str | Sequence[str] | None = "7d0785af3657"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
