"""add phone

Revision ID: f02e0e1a7f8e
Revises: 29f7367ee631
Create Date: 2026-08-06 11:15:02.169282

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "f02e0e1a7f8e"
down_revision: str | Sequence[str] | None = "29f7367ee631"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
