"""create courses table

Revision ID: 1bbc3c13327f
Revises: 33e5296479e2
Create Date: 2026-08-06 12:12:26.891631

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "1bbc3c13327f"
down_revision: str | Sequence[str] | None = "33e5296479e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
