"""create users table

Revision ID: 29f7367ee631
Revises: 84acca45d94e
Create Date: 2026-08-06 11:11:59.908258

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "29f7367ee631"
down_revision: str | Sequence[str] | None = "84acca45d94e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.Enum("ADMIN", "TEACHER", "STUDENT", name="userrole"),
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "create_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "update_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "update_at")
    op.drop_column("users", "create_at")
    op.drop_column("users", "role")
    # ### end Alembic commands ###
